name: wom_pocket
description: A new Flutter application.
publish_to: none

version: 1.4.3+58

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  firebase_analytics: ^10.7.4

  # Locale data
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.11+1
  path_provider: ^2.1.1
  path: ^1.8.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  equatable:
  uni_links: ^0.5.1
  encrypt: ^5.0.3
  mobile_scanner: ^3.5.5
  qr_flutter: ^4.1.0
  intl: ^0.18.1
  dart_geohash: ^2.0.2
  http: ^1.1.2
  intro_views_flutter: ^3.2.0
  webview_flutter: ^4.4.2
  flutter_lock_screen: ^2.0.1
  #  clustering_google_maps: ^0.1.2-nullsafety.3
  google_maps_cluster_manager: ^3.0.0+1
  google_maps_flutter: ^2.5.0
  auto_size_text: ^3.0.0
  flare_flutter: ^3.0.2
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_slidable: ^3.0.1
  share: ^2.0.4
  rflutter_alert: ^2.0.7
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.2.2
  feature_discovery: ^0.14.1
  package_info: ^2.0.2
  pull_to_refresh: ^2.0.0
  #  device_preview: ^0.7.4
  sliding_up_panel: ^2.0.0+1
  logger: ^1.1.0
  pin_code_fields: ^8.0.1
  geolocator: ^10.1.0
  animate_do:
  carousel_slider: ^4.2.1
  toggle_switch: ^2.1.0
  json_annotation: ^4.8.1
  flutter_archive: ^6.0.0
  device_info_plus: ^9.1.1
  cached_network_image:
  dart_wom_connector:
    path: /Users/gianmarcodifrancesco/Work/Digit/Dart/dart_wom_connector
  fl_chart: ^0.65.0
  store_redirect: ^2.0.1
  readmore: ^2.2.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  dots_indicator: ^3.0.0
  oktoast: ^3.4.0
  flutter_cache_manager:
  freezed_annotation:
  dio:

  # UI
  material_design_icons_flutter: ^7.0.7296

dependency_overrides:
  state_notifier: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.14.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed:
  riverpod_generator: ^2.3.9
  custom_lint:
  riverpod_lint:

flutter:

  uses-material-design: true

  assets:
    - assets/images/donation.jpeg
    - assets/images/cities/urbino.jpeg
    - assets/images/cities/pesaro.jpeg
    - assets/images/cities/fano.webp
    - assets/images/empty_wom.png
    - assets/images/wom_pos_pin.png
    - assets/images/1.0x/wom_pos_pin.png
    - assets/images/2.0x/wom_pos_pin.png
    - assets/images/3.0x/wom_pos_pin.png
    - assets/images/migration.png
    - assets/images/logo.png
    - assets/images/logo_1.png
    - assets/images/banking.png
    - assets/images/piggy-bank.png
    - assets/images/best-seller.png
    - assets/images/store.png
    - assets/images/shop.png
    - assets/images/team.png
    - assets/images/m1.png
    - assets/images/m2.png
    - assets/images/m3.png
    - assets/images/m4.png
    - assets/images/wom.png
    - assets/images/wom_pin.png
    - assets/images/wom-pocket-icon.svg
    #    - assets/images/migration.png
    - assets/flare/check.flr
    - assets/registry.pub
    - assets/registry_dev.pub
    - assets/map_style.txt
    - lang/en.json
    - lang/it.json