name: wom_pocket
description: A new Flutter application.
publish_to: none

version: 1.9.8+140

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  contacts_service: ^0.6.3

  # Locale data
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.11+1
  path_provider: ^2.1.5
  path: ^1.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  android_intent_plus: ^5.2.1

  extended_image: ^9.1.0
  image_editor: ^1.6.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  equatable:
  uni_links: ^0.5.1
  encrypt: 5.0.3
  mobile_scanner: ^4.0.1
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  dart_geohash: ^2.1.0
  http: ^1.1.2
  webview_flutter: ^4.10.0
  flutter_lock_screen: ^2.0.1
  google_maps_cluster_manager_2: ^3.2.0
  google_maps_flutter: ^2.10.0
  auto_size_text: ^3.0.0
  rive: ^0.13.20
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_slidable: ^3.0.1
  share: ^2.0.4
  rflutter_alert: ^2.0.7
  internet_connection_checker: ^3.0.1
  url_launcher: ^6.3.1
  package_info: ^2.0.2
  pull_to_refresh: ^2.0.0
  #  device_preview: ^0.7.4
  sliding_up_panel: ^2.0.0+1
  logger: ^2.1.0
  pin_code_fields: ^8.0.1
  geolocator: ^10.1.0
  animate_do:
  carousel_slider: ^5.0.0
  toggle_switch: ^2.1.0
  json_annotation: ^4.9.0
  flutter_archive: ^6.0.3
  device_info_plus: ^11.2.0
  cached_network_image: ^3.3.1
  dart_wom_connector:
    path: /Users/gianmarcodifrancesco/Work/Digit/Dart/dart_wom_connector
  fl_chart: ^0.66.0
  store_redirect: ^2.0.3
  readmore: ^3.0.0
  google_fonts: ^6.3.0
  flutter_svg: ^2.0.9
  dots_indicator: ^3.0.0
  oktoast: ^3.4.0
  flutter_cache_manager:
  freezed_annotation:
  dio:
  easy_localization: ^3.0.7+1
  nfc_manager:
  nfc_background:
    path: /Users/gianmarcodifrancesco/Work/Digit/nfc_background
  flutter_sticky_header: ^0.7.0
  material_design_icons_flutter: ^7.0.7296
  sentry_flutter:
  flutter_riverpod:
  collection: any
  meta:
  go_router:
  validatorless: ^1.2.4
  form_builder_validators: ^11.1.2
  hexagon: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.24.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  riverpod_generator: ^2.6.3
  custom_lint:
  riverpod_lint: ^2.6.3
  delete_un_used_assets: ^1.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/cities/
    - assets/images/1.0x/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/flare/
    - assets/registry.pub
    - assets/registry_dev.pub
    - assets/map_style.txt
    - assets/lang/