name: wom_pocket
publish_to: none
description: A new Flutter application.

version: 1.10.1+146

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  android_intent_plus: ^6.0.0
  animate_do: any
  app_links: ^7.0.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  clippy_flutter: ^2.0.0-nullsafety.1
  collection: any
#  contacts_service: ^0.6.3
  dart_geohash: ^2.1.0
  dart_wom_connector:
    path: /Users/gianmarcodifrancesco/Work/Digit/Dart/dart_wom_connector
  device_info_plus: ^11.2.0
  device_preview: ^1.2.0
  dio: any
  dots_indicator: ^3.0.0
  drift: ^2.28.2
  easy_localization: ^3.0.7+1
  encrypt: 5.0.3
  equatable: any
  extended_image: ^9.1.0
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.3
  flutter_cache_manager: any
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  flutter_lock_screen: ^2.0.1
  flutter_riverpod:
  flutter_slidable: ^3.0.1
  flutter_sticky_header: ^0.7.0
  flutter_svg: ^2.0.9
  form_builder_validators: ^11.1.2
  freezed_annotation: ^3.1.0
  geolocator: ^14.0.2
  go_router: any
  google_fonts: ^6.3.0
  google_maps_cluster_manager_2: ^3.2.0
  google_maps_flutter: ^2.10.0
  hexagon: ^0.2.0
  hive_ce: ^2.2.3
  hive_ce_flutter: any
  hooks_riverpod: ^3.1.0
  http: ^1.1.2
  image_editor: ^1.6.0
  image_picker: ^1.1.2
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.1.0
  material_design_icons_flutter: ^7.0.7296
  meta: any
  mobile_scanner: ^4.0.1
  nfc_background:
    path: /Users/gianmarcodifrancesco/Work/Digit/nfc_background
  nfc_manager: ^4.1.1
  nfc_manager_ndef: ^1.1.0
  oktoast: ^3.4.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  readmore: ^3.0.0
  rflutter_alert: ^2.0.7
  rive: ^0.13.20
  riverpod_annotation: ^4.0.0
  sentry_flutter: any
  share_plus:
  sliding_up_panel: ^2.0.0+1
  sqlite3_flutter_libs: ^0.5.40
  store_redirect: ^2.0.4
  toggle_switch: ^2.1.0
  url_launcher: ^6.3.2
  validatorless: ^1.2.5
  webview_flutter: ^4.13.0

dependency_overrides:
  test: ^1.0.0
  test_api: ^0.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.9.0
  custom_lint: any
  delete_un_used_assets: ^1.0.1
  drift_dev: ^2.24.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  freezed: ^3.2.3
  hive_ce_generator: any
  json_serializable: ^6.8.0
  pubspec_dependency_sorter: ^1.0.5
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.1.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/cities/
    - assets/images/1.0x/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/flare/
    - assets/registry.pub
    - assets/registry_dev.pub
    - assets/map_style.txt
    - assets/lang/
