name: pocket
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.1.2+12

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  uni_links: ^0.2.0
  sqflite: ^1.1.5
  simple_rsa: ^0.0.5
  encrypt: ^3.1.0
  mmkv_flutter: ^1.0.10 #per salvare le preferenze (firstOpen ecc) + veloce delle normali shared preference
  barcode_scan: ^1.0.0
  rxdart: ^0.22.0
  intl:
  intl_translation:
  flutter_map: ^0.3.0
  geohash: ^0.2.1
  http: ^0.12.0
  intro_views_flutter: ^2.4.0
  webview_flutter: ^0.2.0
  flutter_lock_screen: ^1.0.5
  clustering_google_maps: ^0.1.2
  auto_size_text: ^2.0.1
  flare_flutter: ^1.5.2
  clippy_flutter: ^1.1.0
  flutter_slidable: ^0.5.3
  share: ^0.6.2
  firebase_crashlytics: ^0.1.0+2
  wom_package:
    git:
      url: git://github.com/WOM-Platform/WOM-Package.git
  sliding_up_panel: ^0.3.5
#  flare_flutter:
#    git:
#      url: git://github.com/2d-inc/Flare-Flutter.git
#      ref: dev
#      path: flare_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/banking.png
    - assets/images/piggy-bank.png
    - assets/images/best-seller.png
    - assets/images/store.png
    - assets/images/shop.png
    - assets/images/team.png
    - assets/images/m1.png
    - assets/images/m2.png
    - assets/images/m3.png
    - assets/images/m4.png
    - assets/images/wom.png
    - assets/images/wom_pin.png
    - assets/flare/check.flr
    - assets/registry.pub
    - assets/registry_dev.pub
    - lang/en.json
    - lang/it.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
