name: wom_pocket
description: A new Flutter application.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.1+37

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  firebase_analytics: ^10.0.7

  # Locale data
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.11+1
  path_provider: ^2.0.11
  path: ^1.8.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  equatable:
  uni_links: ^0.5.1
  encrypt: ^5.0.1
  mobile_scanner: ^3.0.0-beta.1
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  dart_geohash: ^2.0.2
  http: ^0.13.5
  intro_views_flutter: ^3.2.0
  webview_flutter: ^3.0.4
  flutter_lock_screen: ^2.0.1
#  clustering_google_maps: ^0.1.2-nullsafety.3
  google_maps_cluster_manager: ^3.0.0+1
  google_maps_flutter: ^2.2.3
  auto_size_text: ^3.0.0
  flare_flutter: ^3.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_slidable: ^0.6.0
  share: ^2.0.4
  rflutter_alert: ^2.0.4
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.1.7
  feature_discovery: ^0.14.1
  package_info: ^2.0.2
#  device_preview: ^0.7.4
  sliding_up_panel: ^2.0.0+1
  logger: ^1.1.0
  pin_code_fields: ^7.4.0
  geolocator: ^9.0.2
  animate_do:
  carousel_slider: ^4.2.1
  toggle_switch: ^2.0.1
  json_annotation: ^4.7.0
  flutter_archive: ^5.0.0
  device_info_plus: ^8.0.0
  cached_network_image:
  dart_wom_connector:
    path: /Users/gianmarcodifrancesco/Work/Digit/Dart/dart_wom_connector
  fl_chart: ^0.55.2
  store_redirect: ^2.0.1
  readmore: ^2.2.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6

dependency_overrides:
  state_notifier: ^0.7.2+1

dev_dependencies:
  drift_dev: ^2.2.0+1
  hive_generator: ^2.0.0
  build_runner: ^2.0.6
  json_serializable: ^6.0.0
  freezed:
  riverpod_generator: ^1.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/urbino.jpeg
    - assets/images/wom_pos_pin.png
    - assets/images/migration.png
    - assets/images/logo.png
    - assets/images/logo_1.png
    - assets/images/banking.png
    - assets/images/piggy-bank.png
    - assets/images/best-seller.png
    - assets/images/store.png
    - assets/images/shop.png
    - assets/images/team.png
    - assets/images/m1.png
    - assets/images/m2.png
    - assets/images/m3.png
    - assets/images/m4.png
    - assets/images/wom.png
    - assets/images/wom_pin.png
    - assets/wom-pocket-icon.svg
#    - assets/images/migration.png
    - assets/flare/check.flr
    - assets/registry.pub
    - assets/registry_dev.pub
    - lang/en.json
    - lang/it.json