name: pocket
description: A new Flutter application.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.2.4+20

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  firebase_analytics: ^8.2.0

  flutter_riverpod: ^1.0.0
  equatable:
  cupertino_icons: ^1.0.3
  uni_links: ^0.5.1
  flutter_bloc: ^7.0.1
  sqflite: ^2.0.0+3
  #simple_rsa: ^0.0.5
  encrypt: ^5.0.0
  #mmkv_flutter: ^1.0.10 #per salvare le preferenze (firstOpen ecc) + veloce delle normali shared preference
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  #barcode_scan: ^1.0.0
  qr_code_scanner: ^0.5.2
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  #intl_translation:
  flutter_map: ^0.13.1
  #geohash: ^0.2.1
  dart_geohash: ^2.0.1
  http: ^0.13.3
  intro_views_flutter: ^3.2.0
  webview_flutter: ^2.0.10
  flutter_lock_screen: ^2.0.1
  clustering_google_maps: ^0.1.2-nullsafety.3
  google_maps_cluster_manager: ^1.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  flare_flutter: ^3.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_slidable: ^0.6.0
  share: ^2.0.4
  rflutter_alert: ^2.0.4
  #data_connection_checker: ^0.3.4
  internet_connection_checker: ^0.0.1+2
  url_launcher: ^6.0.9
  feature_discovery: ^0.14.0
  package_info: ^2.0.2
  device_preview: ^0.7.4
  sliding_up_panel: ^2.0.0+1
  logger: ^1.0.0
  pin_code_fields: ^7.3.0
#  location: ^4.3.0
  geolocator: ^7.7.1
  dart_wom_connector:
    path: /Users/gianmarcodifrancesco/Work/Digit/Dart/dart_wom_connector

  store_redirect: ^2.0.1
#  flare_flutter:
#    git:
#      url: git://github.com/2d-inc/Flare-Flutter.git
#      ref: dev
#      path: flare_flutter

dependency_overrides:
  meta: 1.4.0
  analyzer: 1.7.0

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  freezed:
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/banking.png
    - assets/images/piggy-bank.png
    - assets/images/best-seller.png
    - assets/images/store.png
    - assets/images/shop.png
    - assets/images/team.png
    - assets/images/m1.png
    - assets/images/m2.png
    - assets/images/m3.png
    - assets/images/m4.png
    - assets/images/wom.png
    - assets/images/wom_pin.png
#    - assets/images/migration.png
    - assets/flare/check.flr
    - assets/registry.pub
    - assets/registry_dev.pub
    - lang/en.json
    - lang/it.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
